WIP: Reimplement the .desktop file handling of the generic opener in awk

diff --git a/scripts/xdg-open.in b/scripts/xdg-open.in
--- a/scripts/xdg-open.in
+++ b/scripts/xdg-open.in
@@ -332,6 +332,308 @@ open_flatpak()
 #-----------------------------------------
 # Recursively search .desktop file
 
+awk_script_open_with_desktop_file="$(cat << 'AWKEOF'
+BEGIN {
+
+	if (uri_arg) {
+		split(uri_arg, split_uri_arg, " ")
+	}
+
+	filec = 0;
+	for (i=1; split_uri_arg[i]; i++) {
+		uri = split_uri_arg[i]
+		uris[i-1] = uri;
+		print "URI: " uri >> "/dev/stderr"
+		file = decode_local_file_uri(uri)
+		if (file) {
+			print "File: " file >> "/dev/stderr"
+			files[filec] = file;
+			filec = filec + 1;
+		}
+	}
+	
+	in_main_section = 0;
+
+	exec_value = 0;
+	icon_value = 0;
+	name_value = 0;
+}
+
+/^\[/ {
+	in_main_section = 0;
+}
+
+$0 == "[Desktop Entry]" {
+	in_main_section = 1
+}
+
+function unescape_value(escaped) {
+	value = ""
+	for (i=1; i<=length(escaped); i++) {
+		char = substr(escaped, i, 1)
+		if (char == "\\") {
+			i = i+1
+			next_char = substr(escaped,i,1);
+			if (next_char == "s") {
+				value = value " ";
+			} else if (next_char == "n") {
+				value = value "\n";
+			} else if (next_char == "t") {
+				value = value "\t";
+			} else if (next_char == "r") {
+				value = value "\r";
+			} else if (next_char == "\\") {
+				value = value "\\";
+			}
+		} else {
+			value = value char
+		}
+	}
+	return value;
+}
+
+function split_exec_value(value, out_args) {
+	argc = 0;
+	in_quote = 0;
+	current_arg = "";
+	next_is_literal = 0;
+	for (i=1; i<=length(value); i++) {
+		char = substr(value,i,1)
+		if (next_is_literal) {
+			next_is_literal = 0;
+			current_arg = current_arg char
+			continue
+		}
+		if (in_quote) {
+			if (char == "\"") {
+				in_quote = 0;
+				out_args[argc] = current_arg;
+				argc = argc + 1;
+				current_arg = "";
+			} else if (char == "\\") {
+				next_is_literal = 1;
+			} else {
+				current_arg = current_arg char
+			}
+		} else {
+			if (current_arg == "" && char == "\"") {
+				in_quote = 1;
+			} else if (char != " ") {
+				current_arg = current_arg char
+			} else if (current_arg != "") {
+				out_args[argc] = current_arg;
+				argc = argc + 1;
+				current_arg = "";
+			}
+		}
+	}
+	if (current_arg != "") {
+		out_args[argc] = current_arg;
+	}
+}
+
+function hex_value(char) {
+	value = char - "0";
+	if (value >= 0 && value < 10) {
+		return value;
+	}
+	value = char - "a";
+	if (value >= 10 && value < 16) {
+		return value;
+	}
+	value = char - "A";
+	if (value >= 10 && value < 16) {
+		return value;
+	}
+	return 0;
+}
+
+function uri_decode(text) {
+	output = ""
+	for (i=1; i<=length(text); i++) {
+		char = substr(text, i, 1);
+		if (char != "%") {
+			output = output char;
+			continue
+		}
+		char_a = substr(text, i+1, 1);
+		char_b = substr(text, i+2, 1);
+		i = i+2;
+		numeric = hex_value(char_a)*16+hex_value(char_b);
+		if (numeric != 0 && numeric != 47) {
+			output = output sprintf("%c", numeric)
+		}
+	}
+	return output;
+}
+
+function decode_local_file_uri(uri) {
+	if (!match(uri, /^file:\/\//)) {
+		return 0;
+	}
+	host = ""
+	path = 0
+	slash_count = 0
+	host_start = 0
+	host_end = 0
+	path_start = 0
+	for (i=1; i<=length(uri); i++) {
+		char = substr(text, i, 1);
+		if (char == "/") {
+			slash_count++;
+			if (slash_count == 2) {
+				host_start = i;
+			}
+			if (slash_count == 3) {
+				path_start = i;
+			}
+			continue
+		} else if (host_start && char == ":") {
+			host_end = i;
+		} else if (char == "?" || char == "#") {
+			if (path_start) {
+				path = substr(uri, path_start, i - path_start)
+			}
+			# ignore that we wouldn't fully parse the hostname in this case,
+			# if the hostname isn't finished here it'll fail anyway.
+			break
+		}
+		if (host_start && host_end) {
+			host = substr(uri, host_start, host_end - host_start);
+		}
+	}
+	# Hostname must either be empty, "localhost" or match local hostname
+	if (host != "" && host != "localhost" && host != hostname) {
+		return 0;
+	}
+	if (path) {
+		return uri_decode(path)
+	}
+	return 0;
+}
+
+function debug(text) {
+	print "DEBUG: " text >> "/dev/stderr";
+}
+
+in_main_section && match($0, /^[^#=\[]+\[?[^=\]]*\]?=/) {
+	index_of_eq = index($0, "=");
+	index_of_bracket_open = index($0, "[");
+	if (index_of_bracket_open && index_of_bracket_open < index_of_eq) {
+		key = substr($0, 1, index_of_bracket_open-1)
+		local = substr($0, index_of_bracket_open+1, index_of_eq-index_of_bracket_open-2);
+	} else {
+		key = substr($0, 1, index_of_eq-1);
+		local = "";
+	}
+	value = substr($0, index_of_eq+1);
+	debug("Key: " key " Local: " local " Value: " value);
+	if (key == "Exec") {
+			exec_value = unescape_value(value);
+	} else if (key == "Icon") {
+		icon_value = unescape_value(value);
+	} else if (key == "Name") {
+		# TODO: handle actual localization
+		if (local == "") {
+			name_value = unescape_value(value)
+		}
+	}
+}
+
+END {
+	if (!exec_value) {
+		print "No Exec= line found in main section of desktop file!" >> "/dev/stderr";
+		exit 1;
+	}
+	print "Unescaped: " exec_value >> "/dev/stderr"
+	split_exec_value(exec_value, args)
+	# Field code expansion
+	expanded_args[0] = "";
+	eargc = 0;
+	already_found_field_code = 0;
+	for (i=0; args[i]; i++) {
+		arg = args[i];
+		debug("Running field code expansion on arg: " arg);
+		if (arg == "%F") {
+			for (j=0; j<length(files); j++) {
+				expanded_args[eargc] = files[j];
+				eargc = eargc + 1;
+			}
+			already_found_field_code = 1;
+			continue
+		} else if (arg == "%U") {
+			for (j=0; j<length(urls); j++) {
+				expanded_args[eargc] = urls[j];
+				eargc = eargc + 1;
+			}
+			already_found_field_code = 1;
+			continue
+		} else if (arg == "%i") {
+			if (icon_value) {
+				expanded_args[eargc] = "--icon"
+				expanded_args[eargc] = icon_value
+				eargc = eargc + 1;
+			}
+			continue
+		}
+		debug("Trying to find in-text field code ...");
+		expanded_arg = ""
+		for (j=1; j<=length(arg); j++) {
+			char = substr(arg,j,1);
+			if (char != "%") {
+				expanded_arg = expanded_arg char
+				continue
+			}
+			j = j+1;
+			char = substr(arg,j,1);
+			debug("Found field code expansion: %" char);
+			if (char == "%") {
+				expanded_arg = expanded_arg "%"
+			} else if (char == "f") {
+				# Take just the first arg for the prototype
+				expanded_arg = expanded_arg files[0];
+			} else if (char == "u") {
+				# Take just the first arg for the prototype
+				expanded_arg = expanded_arg uris[0];
+			} else if (char == "c") {
+				if (name_value) {
+					expanded_arg = expanded_arg name_value
+				}
+			} else if (char == "k") {
+				# Location of desktop file either as URI or local filename
+				# Ignore for now
+				# TODO
+			} else if (char == "d" || char == "D" || char == "n" || char == "N") {
+				# Deprecated, silently remove
+			} else if (char == "i" || char == "U" || char == "F") {
+				print "Field code %" char "must be stand alone as it expands into multiple arguments!" >> "/dev/stderr";
+				exit
+			} else {
+				print "Unknown field code: %" char "in Exec key!" >> "/dev/stderr";
+				exit 1
+			}
+		}
+		expanded_args[eargc] = expanded_arg;
+		eargc = eargc + 1;
+	}
+
+	
+	for (i=0; expanded_args[i]; i++) {
+		print "Arg: " expanded_args[i] >> "/dev/stderr";
+		printf("%s\0", expanded_args[i]);
+	}
+	print "---" >> "/dev/stderr";
+	exit
+}
+AWKEOF
+)"
+
+# (desktop_file, url)
+open_with_desktop_file()
+{
+	awk -v"hostname=$(get_hostname)" -v"uri_arg=$2" "$awk_script_open_with_desktop_file" < "$1" | xargs -0 -x sh -c 'exec "$@"' -
+}
+
 #(application, directory, target file, target_url)
 search_desktop_file()
 {
@@ -349,62 +651,8 @@ search_desktop_file()
     fi
 
     if [ -r "$file" ] ; then
-        command="$(get_key "${file}" "Exec" | first_word)"
-        if command -v "$command" >/dev/null; then
-            icon="$(get_key "${file}" "Icon")"
-            # FIXME: Actually LC_MESSAGES should be used as described in
-            # http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s04.html
-            localised_name="$(get_key "${file}" "Name")"
-            #shellcheck disable=SC2046 # Splitting is intentional here
-            set -- $(get_key "${file}" "Exec" | last_word)
-            # We need to replace any occurrence of "%f", "%F" and
-            # the like by the target file. We examine each
-            # argument and append the modified argument to the
-            # end then shift.
-            local args=$#
-            local replaced=0
-            while [ $args -gt 0 ]; do
-                case $1 in
-                    %[c])
-                        replaced=1
-                        arg="${localised_name}"
-                        shift
-                        set -- "$@" "$arg"
-                        ;;
-                    %[fF])
-	                    # if there is only a target_url return,
-	                    # this application can't handle it.
-	                    [ -n "$target" ] || return
-                        replaced=1
-                        arg="$target"
-                        shift
-                        set -- "$@" "$arg"
-                        ;;
-                    %[uU])
-                        replaced=1
-                        # When an URI is requested use it,
-                        # otherwise fall back to the filepath.
-                        arg="${target_uri:-$target}"
-                        shift
-                        set -- "$@" "$arg"
-                        ;;
-                    %[i])
-                        replaced=1
-                        shift
-                        set -- "$@" "--icon" "$icon"
-                        ;;
-                    *)
-                        arg="$1"
-                        shift
-                        set -- "$@" "$arg"
-                        ;;
-                esac
-                args=$(( args - 1 ))
-            done
-            [ $replaced -eq 1 ] || set -- "$@" "${target:-$target_uri}"
-            env "$command" "$@"
-            exit_success
-        fi
+		open_with_desktop_file "$file" "$target_uri"
+		exit_success
     fi
 
     for d in "$dir/"*/; do
